<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>edu.utexas.tacc.tapis</groupId>
    <artifactId>tapis-client-java</artifactId>
    <version>2.0.166</version>
  </parent>

  <artifactId>tokens-client</artifactId>

  <name>Tapis Tokens Client</name>
  <description>Java client for Tokens Service</description>

  <properties>
    <!-- Location of openapi spec. Default is dev branch -->
    <!-- NOTE: In order to try out openapi updates using a local file do something similar to the following:
         mvn clean install
         mvn install -DtokensSpecPath="file:///home/scblack/src_git/github/tapis/tokens/service/src/main/resources/openapi_v3.yml"

              or if yaml committed to local branch then do:
         mvn install -DtokensSpecPath="https://raw.githubusercontent.com/tapis-project/tokens-api/dev/service/resources/openapi_v3.yml"
     -->
    <tokensSpecPath>https://raw.githubusercontent.com/tapis-project/tokens-api/dev/service/resources/openapi_v3.yml</tokensSpecPath>
    <target.spec.format>json</target.spec.format>
  </properties>

  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>shared-clientlib</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <sourceDirectory>src/main/java</sourceDirectory>

    <!-- NOTE: THE CALLED SCRIPT INTRODUCES HIDDEN DEPENDENCIES -->
    <!--       These dependencies include Docker and curl.      -->
    <plugins>
      <!-- Capture the git commit hash and branch identifiers. -->
      <!-- See parent pom for configuration details. -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>buildnumber-maven-plugin</artifactId>
      </plugin>
      <!-- Extract artifact prefix before '-client' -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>3.4.0</version>
        <executions>
          <execution>
            <id>regex-property</id>
            <phase>initialize</phase>
            <goals>
              <goal>regex-property</goal>
            </goals>
            <configuration>
              <name>artifact.prefix</name>
              <value>${project.artifactId}</value>
              <regex>^([^-]+)-.*$</regex>
              <replacement>$1</replacement>
              <failIfNoMatch>false</failIfNoMatch>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- Run script to download latest app openapi_v3.yml and generate bundled json file  -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>${exec-maven-plugin.version}</version>
        <executions>
          <execution>
            <id>Generate bundled openapi json file</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>exec</goal>
            </goals>
            <configuration>
              <executable>${basedir}/../gen_spec.sh</executable>
              <arguments>
                <argument>${artifact.prefix}</argument>
                <argument>${tokensSpecPath}</argument>
                <argument>${target.spec.format}</argument>
              </arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- Build generated client code using openapi-generator -->
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>${openapi-generator-maven-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/target/openapi_v3.${target.spec.format}</inputSpec>
              <enablePostProcessFile>true</enablePostProcessFile>
              <generateAliasAsModel>true</generateAliasAsModel>
              <output>${project.build.directory}/generated-sources/openapi</output>
              <generatorName>java</generatorName>
              <groupId>edu.utexas.tacc.tapis</groupId>
              <invokerPackage>edu.utexas.tacc.tapis.tokens.client.gen</invokerPackage>
              <apiPackage>edu.utexas.tacc.tapis.tokens.client.gen.api</apiPackage>
              <modelPackage>edu.utexas.tacc.tapis.tokens.client.gen.model</modelPackage>
              <generateApiTests>false</generateApiTests>
              <generateApiDocumentation>false</generateApiDocumentation>
              <generateModelTests>false</generateModelTests>
              <generateModelDocumentation>false</generateModelDocumentation>
              <configOptions>
                <sourceFolder>src/gen/java/main</sourceFolder>
                <dateLibrary>java8</dateLibrary>
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>

    <finalName>tokens-client</finalName>
  </build>

</project>
